defmodule Writer do
    @moduledoc """
    Returns a path to output assembly file and writes the assembly file.
    """
    @doc """
    Writes the assembly file (```code.s```), using the code generated by `CodeGenerator.generateCode/1`, to the current directory.
    
    ### Specs  
    ```code```is the assembly code generated by the `CodeGenearator.generateCode/1`
    """
    def write_file(code) do
        route = "./code.s"
        File.write(route, code)
        route
    end
end
